Pataisome, kad veiktų React Hello world pavyzdys
Klaidą buvo galima patyti per Naršyklės konsolę:
  ReferenceError: ReactDOM is not defined

Esmė: React'ą turėjome node_modules (prsiminkime yarn... komandą), bet WebPack Encore nežinojo, kad reikia jį įtraukti.

Dokumentacija (neatsimenu, kur radau, bet čia geras pavyzdys):
  https://artemzhuravlev.com/blog/symfony-reactjs-using-encore/

Bonus per konsole siūlo (ir programuoti padės):
  Download the React DevTools for a better development experience: https://fb.me/react-devtools

(cherry picked from commit 96a2931)