Bandome siųsti AJAX užklausą, bet gauname klaidą
Keičiant laukelio turinį, grąžina:
  Error: Error: Request failed with status code 400

Dokumentacija:
  https://www.npmjs.com/package/axios

(cherry picked from commit 58785a1)